sudo: required
language: java

jdk:
  - oraclejdk8

notification:
  email:
    recipients:
      - syhily@gmail.com
    on_success: always
    on_failure: always

after_success:
  - bash .travis_after_success.sh

cache:
  directories:
    - "$HOME/.m2/repository"
